os: windows
language: python

branches:
  only:
    - master
python:
  - "3.8"

services:
  - docker

  before_script: pip install docker-compose

  script:
    - docker-compose run app sh -C "python manage.py test && flake8"
